Delete keys that cannot be updated
When calling the following line:
File "/home/raphael/ccp/ccp/app/ccp_app_back_to_back.py", line 49, in <module>
    st.session_state.update(session_state_data)

The app would throw the following error:
StreamlitAPIException: st.session_state.FormSubmitter:my-form-Load Data
cannot be modified after the widget with key FormSubmitter:my-form-Load
Data is instantiated.

Since this keys cannot be updated we have to remove then from the loaded
state.