Handle convergence error for specific update
The following update causes a convergence error in REFPROP:
comp_e = {
    "methane": 30.241,
    "ethane": 3.639,
    "propane": 2.119,
    "n-butane": 0.7,
    "i-butane": 0.31,
    "n-pentane": 0.39,
    "i-pentane": 0.15,
    "n-hexane": 0.08,
    "nitrogen": 0.25,
    "h2s": 0.02,
    "co2": 62.101,
}
suc_e = ccp.State.define(p=Q_(145, "bar"), T=Q_(42.2, "degC"), fluid=comp_e)
suc_e.update(rho=405.4197781472575, s=2004.9031527899563)

ValueError: DmolarSmolar: [DSFL2 error 226] 2-phase iteration did not
converge.

CoolProp has a .specify_phase method, but for some reason the following
code still gives an error:
s = CP.AbstractState(
    "REFPROP",
    "METHANE&ETHANE&PROPANE&BUTANE&ISOBUTAN&PENTANE&IPENTANE&HEXANE&NITROGEN&H2S&CO2",
)
s.set_mole_fractions(
    [
        0.30241,
        0.03639,
        0.02119,
        0.006999999999999999,
        0.0031,
        0.0039000000000000003,
        0.0015,
        0.0008,
        0.0025,
        0.0002,
        0.62101,
    ]
)
s.specify_phase(CP.iphase_gas)
s.update(CP.DmassSmass_INPUTS, 405.4197781472575, 2004.9031527899563)

The time that goes into calling the routine that does not converge is:
8.69 s ± 66.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

And the time used when we force the phase to vapor is:
64.6 µs ± 483 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In the future it would be interesting to have a State class directly
linked to the REFPROP wrapper to have more control on calculations and
also have some improvements in speed.