Replace my-form with my_form
For some reason when calling the following line:
File "/home/raphael/ccp/ccp/app/ccp_app_back_to_back.py", line 49, in <module>
    st.session_state.update(session_state_data)

The app would throw the following error:
StreamlitAPIException: st.session_state.FormSubmitter:my-form-Load Data
cannot be modified after the widget with key FormSubmitter:my-form-Load
Data is instantiated.

Maybe something related with not being able to update with names that
do not work with how attributes are set (e.g. st.session_state.s-1 = 0
fails.)